### ISSUE TITLE
API Goals?

### ISSUE THREAD

**Issue by ZexaronS** [tgjones/OpenSAGE#1]
Hello

Noticed your attempt to improve GenZH, however while you said you have similar but different goals, I don't see anywhere what those specifically are. I was following Thyme for most of this year, but I can't really do anythign as I don't have deep C++ knowledge, the creator of Thyme recently said it's 1-2% done, I don't know if he meant total progress or just his deep C++ work, that to me sounds like slow progress considering this is going for 6 months now, if it takes too long I am afraid the community that is left might lose interest and dry up in the next 4 years, especially some of the younger (exceptions) ones that might be enjoying GenZH, I don't think it's just superhardcore old cats still playing every day.

I don't play much simply because I'm way too demanding user, I'm a technical geek and I just can't stand laggyness and mismatches.

So my goal is to fix the hard bugs that are limiting modding as well as AI bugs that are present without modding and may or may not be able to be fixed by just INI modding, fixing the underhood of AI scripts to make sure it's optimized, and then moving off DX8 and jumping ahead to Vulkan.

Personally I don't mind much about multiplatform however I agree others probably do want it eventually, so it would be Win7, Win10 and MAC and maybe 2 most common linux distros, if MAC can't have Vulkan that's their problem, so one less thing to deal with. Plus Win7/Win10 don't need separate compilation anyway.

Thyme is focusing on MAC support that's the primary reason of using OGL 3.2 or something, I'm simply not a fan of supporting old stuff nor have any interest in MAC, and I don't want to deal with an old API when there is a new shiny high-performance one out now, I want to see hundreds/thousands of units and all the effects/particles in Generals Zero Hour WITHOUT LAG at 60FPS at 1440p. And playing against 8 AIs and huge bases all without LAG. 

Infact if something like this would be started, I'd focus on Win-64 build anyway cause there's really no need for multiplatform when I can put a 50Euro HDD into any PC an install the necessary OS to play, similarly to how I use Win10 on another HDD just to play DCSWorld smoothly (not working good on Win7 for me) It's just a non issue.

**Comment by tgjones** [comment]
Hi @ZexaronS :)

> Noticed your attempt to improve GenZH

I very much doubt I could improve on Generals / Zero Hour! I'm just trying to do an open-source re-implementation of these great games. At this stage, that is my only goal: to make an open-source engine that can use the data from Generals / Zero Hour, to make sure that people who love these games can continue to play them in the future.

>  the creator of Thyme recently said it's 1-2% done

That sounds about right to me, and probably applies to OpenSAGE too. C&C Generals and Zero Hour were *huge* games, created by large teams of people. The odds are against being able to recreate them with just one or developers working on it as a hobby, but it's fun to try.

> So my goal is to fix the hard bugs that are limiting modding as well as AI bugs

You're skipping ahead a bit :) There needs to be a complete re-implementation of the game as it already exists, before enhancements can be made. Of course, since OpenSAGE is a ground-up re-implementation, there's no need to recreate bugs along the way, but in terms of modifying behaviour or adding features, that is a long way off.

It's great that you're interested in OpenSAGE :) I just want to set expectations quite low, because although I've made good progress in the 4 months I've been working on it, I'm really only just getting started.
